### ISSUE TITLE
FIP-14: Ensuring API response data integrity comments

### ISSUE THREAD

**Issue by pawmmm** [fioprotocol/fips#102]
Please comment on FIP-14 here.

**Comment by cc32d9** [comment]
One fundamental drawback of proposed solution is that it doesn't offer a client to determine the authenticity of API results automonously. It needs to go through a complex set of requests to verify the data, which affects the scalability of the service.

Ideally, the smart contract data would already contain signatures (like in PGP) that allow the client to verify the integrity and authenticity. But that requires a full re-do of the whole protocol.

So, my proposal is to build a system of add-on information that lets the client verify the API output in minimal time, and using only a single API endpoint. The method should also not change if a third-party operator sets up their own nodes for their users.

The primary purpose of the FIO API is to provide a mapping between a user@domain account and cryptocurrency addresses, such as BTC or ETH. thus, the solution should protect this information from man-in-the-middle attacks and rogue API service.

In this proposal, a certificate is a data element similar to X.509 certificates: the original data, such as a public key, is signed by a higher authority's key. certificates have expiration dates. Unlike X.509, they may include multiple signatures by higher authorities.

The design defines 3 levels of certificates:

* Root level: a certificate containing BP keys, cross-signed by at least 15 active producers. These certificates form a file-based chain, so that every change in the list refers to the previous version and gets at least 15 signatures from the previous list. So, the wallet software needs to have only the first certificate hardcoded or pre-distributed, and all updates can be downloaded from a public carrier, such as FIO chain itself. As new producers are moving into top 21, their keys are added to the new version of the certificate. The keys of producers which are pushed down the list are still preserved in the list for validating the signatures from the past. The list of keys contains also a revocation list: those keys which were compromised and all their signatures must be rejected.

* Account level certitifates: they are issued by active BP, and the authority is verified through the root certificate. The account certificate states the FIO public key and FIO account name@domain. Only one signature of an active BP is sufficient. If other players detect invalid data being signed, the BP key gets into the revocation lust, and all its signed data is invaluidated.


* Cryptocurrency address level: the user signs their own addresses with their key. 

These certiticates are stored in FIO chain memory. it is important too note that they can also be stored elsewhere, and the blockchain is simply a convenient way to deliver the data.


So, the API would implement new requests that deliver certificate chains accordingly, so that the wallet software can validate the output. The certificates woudl be cached on the client side, so the APi traffic overhead is quite moderate.

The client software is supposed to have the initial root certificate, pre-installed in a trusted way. 

The following API requests would be needed:

* `get_root_certs`. Input argument is the serial number of the root certificate that the client has. the API returns a number of root certificates in their sequential order, so that the client can request more if the chain is too big. The client caches the results in non-volatile memory.

* `get_account_cert`. Input argument is `user@domain` or the EOSIO account name, and the output is a copy of the account certificate. the client normally stores for long term, probably maintaining an eviction list to clean up its storage.

* `get_addres_certs`. The input argument is `user@domain` and a list of cryptocurrency addresses needing verification. The result is a set of cryptocurrency level certificates that can be stored in the client.


Once a client receives an invalid certificate or invalid data that is not confirmed by a certificate, it can report the potential fraud on-chain, supplying all the details of the API call and returned results. This will allow the BP to set up a monitoring infrastructure that will react immediately on such alerts.

**Comment by pawmmm** [comment]
My concern with this approach is that if a single BP is successfully attacked, the attacker can issue a valid account-level certificate and then modify responses from its API and all that while producing valid blocks. It may be a while before someone notices the attack, reports it and BPs revoke the certificate of that BP. Because of that the reader can never be certain the response is valid.

**Comment by cc32d9** [comment]
it needs thinking, but one of possible ways is multiple signatures on account-level certicates. For example, 3 random different producers need to sign them before they become valid. Also the certificates can have a sequence number and a hash of previous certificate, and the contract would control that the next certificate is signed by a 3 different producers than the last one.

**Comment by lukestokes** [comment]
I'd also like us to consider existing solution providers that may be handling similar challenges such as https://www.pokt.network/ or https://liquidapps.io/ (in how they validate vRAM data)

**Comment by edrotthoff** [comment]
greetings team -- im getting oriented on FIP-14 and will try to make some documentation that will help to facilitate further discussion and evaluation of these options....

**Comment by edrotthoff** [comment]
thanks for the summary @cc32d9 its appreciated..great detail you have provided..

**Comment by pawmmm** [comment]
This discussion is being moved to: https://fioprotocol.atlassian.net/browse/WP-103
