### ISSUE TITLE
Include first version implementing the FIP in README.md 

### ISSUE THREAD

**Issue by blockpane** [fioprotocol/fips#104]
Would it be possible to include the chaincode or contract release where a FIP became available in the table showing description and acceptance status?

**Comment by pawmmm** [comment]
There is Final status means it has been accepted and deployed. What exactly would you like to see? Link to release?

**Comment by tagdapix** [comment]
A mention to the upcoming release or when it was merged. Kowning when it's coming could help with planning sdk updates or client updates. Also it would be useful for tracking what's in Testnet. 

I did *not* notice the "Final" status, since we haven't hit that benchmark yet. It'd be nice to have, but if you don't think it's worth the extra we can close this :)

**Comment by pawmmm** [comment]
I already plan to transition to Final status, so adding list to release is no big. @ericbutz maybe you should own transitioning the FIP to Final and adding release?

**Comment by ericbutz** [comment]
Makes sense. I can add this info for release.

**Comment by levi-rahman** [comment]
Thanks.

**Comment by levi-rahman** [comment]
What should I do next?

**Comment by ericbutz** [comment]
@levi-rahman, the fips repos simply tracks the status of fio improvement features. If you want to work on FIO projects you can keep on eye out for Opportunities on the FIO Community board. https://fioprotocol.atlassian.net/wiki/spaces/FC/overview

**Comment by pawmmm** [comment]
Closing as resolved.
